services:
  - type: web
    name: xyz-thanks-bot
    runtime: python
    region: singapore
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app & python3 bot.py

    envVars:
      - key: api_id
        sync: false
      - key: api_hash 
        sync: false
      - key: bot_token
        sync: false

    plan: free
